name: hnh
description: Hotter'n Hell Hundred event app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  rxdart: ^0.20.0
  mockito: ^4.0.0

  # user location
  location: ^2.3.5
  

  http: ^0.12.0+1
  shared_preferences: ^0.5.0
  logging: ^0.11.3+2
  uuid: ^2.0.0
  # UI
  modal_progress_hud: ^0.1.2

  # Google Maps Provider
  # google_maps_flutter: 
  #   git:
  #     url: git://github.com/awazgyawali/plugins/
  #     path: packages/google_maps_flutter
  #     ref: cd06409
  google_maps_flutter: ^0.5.6
  # Do not change this version to anything newer for now due to AndroidX dependency issues
  webview_flutter: '0.3.3'

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1

  # For creation of the Launcher Icons
  flutter_launcher_icons: ^0.7.0
  
flutter_icons:
  image_path_android: "assets/img/icon.png"
  image_path_ios: "assets/img/icon.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # images
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-Italic.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
